name: "MPC Energy Dev"
description: "A profit optimiser for home batteries with wholesale electricity pricing."
version: "0.7.203"
slug: "mpc_energy"
url: "https://github.com/4tiernan/mpc_energy" #HA URL for dev branch: https://github.com/4tiernan/mpc_energy#dev 
init: false
arch:
  - amd64
  - aarch64

hassio_api: true 
homeassistant_api: true

ingress: true
ingress_port: 8501

panel_icon: mdi:chart-line

services:
  - mqtt:need

map:
  - type: addon_config
    read_only: false

startup: services

options: {}
schema: {}
