name: "MPC Energy Dev"
description: "A profit optimiser for home batteries with wholesale electricity pricing."
version: "0.7.133"
slug: "mpc_energy"
url: "https://github.com/4tiernan/mpc_energy" #HA URL for dev branch: https://github.com/4tiernan/mpc_energy#dev 
init: false
arch:
  - amd64
  - aarch64

hassio_api: true 
homeassistant_api: true

ingress: true
ingress_port: 8501

panel_icon: mdi:chart-line

services:
  - mqtt:need

map:
  - type: addon_config
    read_only: false

startup: services


options:
  accepted_risks: False
  ha_mqtt_user: ""
  ha_mqtt_pass: ""

  energy_retailer: "amber"
  demand_price: ""
  demand_window_start: "16:00"
  demand_window_end: "21:00"

  amber_api_key: ""
  amber_site_id: ""

  flow_import_price_entity_id: ""
  flow_export_price_entity_id: ""
  flow_price_forecast_entity_id: ""

  battery_discharge_cost: 7
  spike_price_warning_level: 25
  notification_target: ""
  notification_target_option: none
  estimated_daily_load_energy_consumption: 24

  solcast_forecast_today_entity_id: "sensor.solcast_pv_forecast_forecast_today"
  solcast_forecast_tomorrow_entity_id: "sensor.solcast_pv_forecast_forecast_tomorrow"
  solcast_forecast_day_3_entity_id: "sensor.solcast_pv_forecast_forecast_day_3"
  solcast_forecast_day_4_entity_id: "sensor.solcast_pv_forecast_forecast_day_4"
  solcast_solar_kwh_remaining_today_entity_id: "sensor.solcast_pv_forecast_forecast_remaining_today"
  solcast_solar_power_this_hour_entity_id: "sensor.solcast_pv_forecast_forecast_this_hour"

  log_level: info


schema:
  accepted_risks: bool

  ha_mqtt_user: str
  ha_mqtt_pass: password
  energy_retailer: list(amber|flow)

  demand_price: str?
  demand_window_start: str?
  demand_window_end: str?

  amber_api_key: password?
  amber_site_id: str?

  flow_import_price_entity_id: str?
  flow_export_price_entity_id: str?
  flow_price_forecast_entity_id: str?

  battery_discharge_cost: int
  spike_price_warning_level: int  
  notification_target: str?
  notification_target_option: list(none|price_spike_warning|error_warning|both)
  estimated_daily_load_energy_consumption: int

  solcast_forecast_today_entity_id: str
  solcast_forecast_tomorrow_entity_id: str
  solcast_forecast_day_3_entity_id: str
  solcast_forecast_day_4_entity_id: str
  solcast_solar_kwh_remaining_today_entity_id: str
  solcast_solar_power_this_hour_entity_id: str


  log_level: list(debug|info|warning)
