name: "MPC Energy Dev"
description: "A profit optimiser for home batteries with wholesale electricity pricing."
version: "0.7.198"
slug: "mpc_energy"
url: "https://github.com/4tiernan/mpc_energy" #HA URL for dev branch: https://github.com/4tiernan/mpc_energy#dev 
init: false
arch:
  - amd64
  - aarch64

hassio_api: true 
homeassistant_api: true

ingress: true
ingress_port: 8501

panel_icon: mdi:chart-line

services:
  - mqtt:need

map:
  - type: addon_config
    read_only: false

startup: services


options:
  accepted_risks: False
  ha_mqtt_user: ""
  ha_mqtt_pass: ""

  battery_discharge_cost: 7
  spike_price_warning_level: 25
  notification_target: ""
  notification_target_option: none
  estimated_daily_load_energy_consumption: 24

  log_level: info


schema:
  accepted_risks: bool

  ha_mqtt_user: str
  ha_mqtt_pass: password

  battery_discharge_cost: int
  spike_price_warning_level: int  
  notification_target: str?
  notification_target_option: list(none|price_spike_warning|error_warning|both)
  estimated_daily_load_energy_consumption: int
  log_level: list(debug|info|warning)
